per_page: 10
requests:
  per_page: 3
admin:
  books:
    per_page: 2
    size: "100x100"
    url: "/assets/images_nil.jpeg"
    pic_size: 5
    round_rate_average: 2
    image_size: 5000000
    avartar_size: "50x50"
users:
  avatar_nil: "/assets/avartar_nil.jpeg"
books:
  size: "200x200"
  size_details: "300x300"
  size_star_details: "30x30"
reivews: ["bad", "poor", "regular", "good", "gorgeous"]
star_on: "/assets/star-on.png"
star_off: "/assets/star-off.png"
