per_page: 10
requests:
  per_page: 3
admin:
  books:
    per_page: 2
    size: "100x100"
    url: "/assets/images_nil.jpeg"
    pic_size: 5
    round_rate_average: 2
    image_size: 5000000
books:
  size: "200x200"
  size_details: "300x300"
